import { ItemDefinition } from './types'

export const CATEGORIES: { id: number; name: string }[] = [
  { id: 0x00, name: '武器 (短剑)' },
  { id: 0x01, name: '武器 (太刀)' },
  { id: 0x02, name: '武器 (巨剑)' },
  { id: 0x03, name: '武器 (光剑)' },
  { id: 0x04, name: '防具 (护肩)' },
  { id: 0x05, name: '防具 (上衣)' },
  { id: 0x06, name: '防具 (下衣)' },
  { id: 0x07, name: '首饰 (手腕)' },
  { id: 0x08, name: '首饰 (戒指)' },
  { id: 0x09, name: '称号' },
  { id: 0x0a, name: '宠物' },
  { id: 0x0b, name: '材料' },
  { id: 0x0c, name: '卡片' },
  { id: 0x0d, name: '消耗品 (HP药剂)' },
  { id: 0x0e, name: '消耗品 (MP药剂)' },
  { id: 0x0f, name: '消耗品 (死塔药剂)' },
  { id: 0x10, name: '消耗品 (BUFF药剂)' },
  { id: 0x11, name: '消耗品 (属性增益)' },
  { id: 0x12, name: '罐子类' },
  { id: 0x13, name: '任务物品' },
]

export const ITEM_DICTIONARY: ItemDefinition[] = [
  // 称号类 (0x09)
  { typeId: 0x09, itemId: 0x08, name: '力体狂暴之冠 (物攻+力体)', categoryName: '称号', quality: 'pink', desc: '物攻+X%, 力+30, 体+40' },
  { typeId: 0x09, itemId: 0x09, name: '智精睿智之耀 (魔攻+智精)', categoryName: '称号', quality: 'pink', desc: '魔攻+X%, 智+30, 精+40' },
  { typeId: 0x09, itemId: 0x0a, name: '锐利破袭之怒 (暴击伤害)', categoryName: '称号', quality: 'orange', desc: '暴击+X%, 暴伤+20%, 打击回复+50' },
  { typeId: 0x09, itemId: 0x0b, name: '芙蕾雅的祝福 (弗蕾亚的祝福)', categoryName: '称号', quality: 'orange', desc: '获得经验+X%, 掉率+30%, HP/MP+8' },
  { typeId: 0x09, itemId: 0x0c, name: '全能战神荣光 (全状态+移速)', categoryName: '称号', quality: 'orange', desc: '全状态+X, 移动+2, HP/MP再生+3' },

  // 宠物类 (0x0a)
  { typeId: 0x0a, itemId: 0x01, name: '亚米 (Yami)', categoryName: '宠物', quality: 'pink', desc: 'HPMax+7%, 暴击+5%' },
  { typeId: 0x0a, itemId: 0x02, name: '贝雷斯普 (巴里斯普)', categoryName: '宠物', quality: 'pink', desc: '物攻+X%, HPMAX+15%, 力量+30' },
  { typeId: 0x0a, itemId: 0x03, name: '佛尔卡斯 (弗尔卡斯)', categoryName: '宠物', quality: 'pink', desc: '魔攻+X%, MPMAX+15%, 智力+30' },
  { typeId: 0x0a, itemId: 0x04, name: '哈长地 (哈尔吉/哈朗蒂)', categoryName: '宠物', quality: 'orange', desc: '全状态+X, 削血10%, 命中+10%' },
  { typeId: 0x0a, itemId: 0x05, name: '汉爬 (旱爬/汉帕)', categoryName: '宠物', quality: 'pink', desc: '暴击+X%, 移动+2, 打击回复+50' },
  { typeId: 0x0a, itemId: 0x06, name: '青龙 (晴龙)', categoryName: '宠物', quality: 'orange', desc: '经验+X%, 物品掉落率+20%, 命中+10%' },
  { typeId: 0x0a, itemId: 0x07, name: '白虎 (White Tiger)', categoryName: '宠物', quality: 'orange', desc: '自动拾取, 金币+10%, HP/MP再生+5' },

  // 材料类 (0x0b)
  { typeId: 0x0b, itemId: 0x01, name: '碎布片', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x02, name: '破皮革 (破旧的皮革)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x03, name: '风化骨片 (风化的碎骨)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x04, name: '生锈铁片 (生锈的铁片)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x05, name: '最下级硬化剂 (最下硬化剂)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x06, name: '最下级砥石 (最下砥石)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x07, name: '2级布片 (普通布片)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x08, name: '2级皮革 (普通皮革)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x09, name: '2级骨片 (普通骨片)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x0a, name: '2级铁片 (普通铁片)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x0b, name: '中级/下级硬化剂', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x0c, name: '中级/下级砥石', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x0d, name: '3级布片 (高级布片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x0e, name: '3级皮革 (高级皮革)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x0f, name: '3级骨片 (高级骨片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x10, name: '3级铁片 (高级铁片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x11, name: '3级硬化剂 (高级硬化剂)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x12, name: '3级砥石 (高级砥石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x13, name: '4级布片 (特级布片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x14, name: '4级皮革 (特级皮革)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x15, name: '4级骨片 (特级骨片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x16, name: '4级铁片 (特级铁片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x17, name: '上级硬化剂 (顶级硬化剂)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x18, name: '上级砥石 (顶级砥石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x19, name: '顶级布片 (极品布片)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x1a, name: '顶级皮革 (极品皮革)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x1b, name: '顶级骨片 (极品骨片)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x1c, name: '顶级铁片 (极品铁片)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x1d, name: '顶级硬化剂 (极品硬化剂)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x1e, name: '顶级砥石 (极品砥石)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x1f, name: '血滴石 (血之石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x20, name: '海蓝宝石 (蓝宝石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x21, name: '金刚石 (钻石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x22, name: '黑耀石 (黑曜石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x23, name: '缟玛瑙 (玛瑙石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x24, name: '火焰石 (火红石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x25, name: '冰结石 (寒冰石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x26, name: '闪光石 (雷光石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x27, name: '黑英石 (暗影石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x28, name: '透明石 (幻彩石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x29, name: '黑色小晶体', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x2a, name: '白色小晶体', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x2b, name: '红色小晶体', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x2c, name: '蓝色小晶体', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x2d, name: '无色小晶体', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x2e, name: '黄金小晶体 (金色小晶体)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x2f, name: '黑色大晶体', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x30, name: '白色大晶体', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x31, name: '红色大晶体', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x32, name: '蓝色大晶体', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x33, name: '无色大晶体', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x34, name: '黄金大晶体 (金色大晶体)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x35, name: '混沌的魔石 (混沌魔石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x36, name: '光辉的魔石碎片 (光辉魔石碎片)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x37, name: '光辉的魔石 (光辉魔石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x38, name: '下级邪念结晶', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x39, name: '中级邪念结晶', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x3a, name: '上级邪念结晶', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x3b, name: '顶级邪念结晶 (特级邪念结晶)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x3c, name: '克尔顿印章 (卡尔顿印章)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x3d, name: '斯卡迪印章 (斯卡迪女皇印章)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x3e, name: '魔法师印章 (魔导士印章)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x3f, name: '撒勒印章 (萨勒印章)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x40, name: '燃烧恶魔的邀请函 (燃烧邀请函)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x41, name: '蓝色恶魔的邀请函 (湛蓝邀请函)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x42, name: '凶猛恶魔的邀请函 (狂暴邀请函)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x43, name: '火焰的破魔石 (火焰破魔石)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x44, name: '蒸汽的破魔石 (蒸汽破魔石)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x45, name: '野生的破魔石 (野生破魔石)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x46, name: '火焰的科斯莫眼 (宇宙之眼·火)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x47, name: '蒸汽的科斯莫眼 (宇宙之眼·气)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x48, name: '野生的科斯莫眼 (宇宙之眼·野)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x49, name: '阿尔比诺碎片 (深渊邀请碎片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x4a, name: '深渊碎片 (深渊的碎片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x4b, name: '塔拉骑士碎片 (骑士碎片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x4c, name: '风愿碎片 (愿望碎片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x4d, name: '下级元素结晶', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x4e, name: '上级元素结晶', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x4f, name: '强烈片 (强烈的痕迹)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x50, name: '魔塔皮亚 (魔塔之晶)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x51, name: '米拉津果实 (米拉津果)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x52, name: '马雷果实 (马雷果)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x53, name: '妖丰骨 (妖精骨/妖风骨)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x54, name: '猫指甲 (暗猫指甲)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x55, name: '黑妖精守护精华 (守护精华)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x5a, name: '黑暗项链 (暗影项链)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x5b, name: '龙人之眼 (龙之眼)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x5c, name: '斯皮内尔 (赤红矿石)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x5d, name: '普罗莱特 (纯净矿石)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x5e, name: '吉尔肯 (紫晶矿石)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x5f, name: '圣痕绸缎 (圣痕丝绸)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x60, name: '无重力碎片', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x61, name: '辛达的水杯 (辛达空杯)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x62, name: '坚硬的触须 (章鱼触须)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x63, name: '锋利的尖刺 (带刺尖刺)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x64, name: '耀眼的结晶 (耀眼结晶)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x65, name: '龙头炮的炮身 (龙头炮身)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x66, name: '邪恶的结晶 (邪恶结晶)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x67, name: '干扰芯片 (微型芯片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x68, name: '压缩胶囊', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x69, name: '不良芯片 (破损芯片)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x6a, name: '藤蔓根 (坚韧藤蔓)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x6b, name: '黑硬物质 (黑色硬块)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x6c, name: '碎片的刀刃 (残破刀刃)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x6d, name: '辛达炉券 (神圣的炉岩炭)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x6e, name: '锋利的狼牙 (尖锐的狼牙)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x6f, name: '雪山虎皮革 (冰虎皮革)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x70, name: '红纸 (神秘红纸)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x71, name: '铁撬 (撬棍)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x72, name: '空水杯 (纯净水杯)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x73, name: '灵魂晶石 (灵魂之石)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x74, name: '泰拉石 (远古泰拉石)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x75, name: '魔力溶解剂 (魔力溶剂)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x76, name: '忘却片 (过去门票/忘却碎片)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x77, name: '破碎的忘却片 (残破忘却碎片)', categoryName: '材料', quality: 'blue' },
  { typeId: 0x0b, itemId: 0x78, name: '阿尔比诺精华 (阿尔比诺门票)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x7b, name: '深渊的精华 (深渊之门票)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x7d, name: '帝国的超精华 (比尔马克门票)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x7f, name: '修炼的项链 (试炼门票)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x80, name: '研磨剂 (高纯度研磨剂)', categoryName: '材料', quality: 'white' },
  { typeId: 0x0b, itemId: 0x81, name: '物品栏扩展卷+5格 (扩展券+5)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x82, name: '物品栏扩展卷+10格 (扩展券+10)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x83, name: '交易许可书 (通行证明)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x84, name: '代币 (复活兑换券)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x85, name: '强化碳 (炉岩炭)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x89, name: '小龙的心脏 (幼龙心脏)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x90, name: '暴龙王戒 (狂龙之戒)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x91, name: '赛菲亚破旧日记 (旧日记)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x92, name: '机械牛装置 (比尔马克机械芯)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x93, name: '死神邀请函 (迷惘之塔邀请函)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x96, name: '奥尔哈肯 (神秘矿精)', categoryName: '材料', quality: 'purple' },
  { typeId: 0x0b, itemId: 0x97, name: '生肖 (远古生肖石)', categoryName: '材料', quality: 'pink' },
  { typeId: 0x0b, itemId: 0x98, name: '封印的力气戒指 (力量魔戒)', categoryName: '材料', quality: 'orange' },
  { typeId: 0x0b, itemId: 0x99, name: '封印的力气手套 (力量手套)', categoryName: '材料', quality: 'orange' },

  // 卡片类 (0x0c)
  { typeId: 0x0c, itemId: 0x65, name: '魔人丹特卡片 (武器)', categoryName: '卡片', quality: 'pink' },
  { typeId: 0x0c, itemId: 0x66, name: '魔人丹特卡片 (肩甲)', categoryName: '卡片', quality: 'pink' },
  { typeId: 0x0c, itemId: 0x67, name: '魔人丹特卡片 (上衣)', categoryName: '卡片', quality: 'pink' },
  { typeId: 0x0c, itemId: 0x68, name: '魔人丹特卡片 (下衣)', categoryName: '卡片', quality: 'pink' },
  { typeId: 0x0c, itemId: 0x69, name: '魔人丹特卡片 (手腕)', categoryName: '卡片', quality: 'pink' },
  { typeId: 0x0c, itemId: 0x6a, name: '魔人丹特卡片 (戒指)', categoryName: '卡片', quality: 'pink' },

  // 属性增益类 (0x11)
  { typeId: 0x11, itemId: 0x14, name: '深渊之眼 (迷宫可视地图)', categoryName: '消耗品', quality: 'orange' },
  { typeId: 0x11, itemId: 0x05, name: '+3 SP技能书', categoryName: '消耗品', quality: 'pink' },
  { typeId: 0x11, itemId: 0x06, name: '+5 SP技能书', categoryName: '消耗品', quality: 'pink' },
  { typeId: 0x11, itemId: 0x0a, name: '+20 SP技能书', categoryName: '消耗品', quality: 'orange' },

  // 任务物品类 (0x13)
  { typeId: 0x13, itemId: 0x98, name: '封印的魔力之痕迹', categoryName: '任务物品', quality: 'purple' },
  { typeId: 0x13, itemId: 0x90, name: '灼热的魔塔皮亚', categoryName: '任务物品', quality: 'purple' },
  { typeId: 0x13, itemId: 0x8e, name: '混沌的魔石(任务)', categoryName: '任务物品', quality: 'purple' },

  // 武器示例 (0x00 短剑, 0x01 太刀, 0x02 巨剑, 0x03 光剑)
  { typeId: 0x01, itemId: 0x09, name: '太刀 (15级稀有)', categoryName: '太刀', quality: 'purple', canRefine: true },
  { typeId: 0x01, itemId: 0x28, name: '流光星陨刀 (太刀)', categoryName: '太刀', quality: 'pink', canRefine: true },
  { typeId: 0x01, itemId: 0x39, name: '月之光芒 (史诗太刀)', categoryName: '太刀', quality: 'orange', canRefine: true },
  { typeId: 0x01, itemId: 0x51, name: '屠戮之刃 (60史诗太刀)', categoryName: '太刀', quality: 'orange', canRefine: true },
  { typeId: 0x02, itemId: 0x50, name: '魔剑-阿波菲斯 (巨剑)', categoryName: '巨剑', quality: 'pink', canRefine: true },
  { typeId: 0x02, itemId: 0x58, name: '逸龙剑-抉择 (史诗巨剑)', categoryName: '巨剑', quality: 'orange', canRefine: true },
  { typeId: 0x03, itemId: 0x50, name: '黑光-雷剑苦轮 (光剑)', categoryName: '光剑', quality: 'pink', canRefine: true },
  { typeId: 0x03, itemId: 0x60, name: '天行者 (史诗光剑)', categoryName: '光剑', quality: 'orange', canRefine: true },
  { typeId: 0x00, itemId: 0x50, name: '破碎之命运 (史诗短剑)', categoryName: '短剑', quality: 'orange', canRefine: true },
  { typeId: 0x00, itemId: 0x60, name: '无影剑-艾雷诺 (史诗短剑)', categoryName: '短剑', quality: 'orange', canRefine: true },
]

// 批量生成防具类 (0x04 护肩, 0x05 上衣, 0x06 下衣)
const ARMOR_DEFS: { id: number; name: string; quality: 'pink' | 'orange' }[] = [
  { id: 0x6d, name: '10级粉布甲', quality: 'pink' },
  { id: 0x6e, name: '10级粉轻甲', quality: 'pink' },
  { id: 0x6f, name: '10级粉重甲', quality: 'pink' },
  { id: 0x70, name: '10级粉板甲', quality: 'pink' },
  { id: 0x71, name: '20级粉布甲', quality: 'pink' },
  { id: 0x72, name: '20级粉轻甲', quality: 'pink' },
  { id: 0x73, name: '20级粉重甲', quality: 'pink' },
  { id: 0x74, name: '20级粉板甲', quality: 'pink' },
  { id: 0x75, name: '30级粉布甲', quality: 'pink' },
  { id: 0x76, name: '30级粉轻甲', quality: 'pink' },
  { id: 0x77, name: '30级粉重甲', quality: 'pink' },
  { id: 0x78, name: '30级粉板甲', quality: 'pink' },
  { id: 0x79, name: '40级粉布甲', quality: 'pink' },
  { id: 0x7a, name: '40级粉轻甲', quality: 'pink' },
  { id: 0x7b, name: '40级粉重甲', quality: 'pink' },
  { id: 0x7c, name: '40级粉板甲', quality: 'pink' },
  { id: 0x7d, name: '50级粉布甲', quality: 'pink' },
  { id: 0x7e, name: '50级粉轻甲', quality: 'pink' },
  { id: 0x7f, name: '50级粉重甲', quality: 'pink' },
  { id: 0x80, name: '50级粉板甲', quality: 'pink' },
  { id: 0x81, name: '60级粉布甲', quality: 'pink' },
  { id: 0x82, name: '60级粉轻甲', quality: 'pink' },
  { id: 0x83, name: '60级粉重甲', quality: 'pink' },
  { id: 0x84, name: '60级粉板甲', quality: 'pink' },

  // 橙装
  { id: 0x85, name: '25级橙布甲', quality: 'orange' },
  { id: 0x86, name: '25级橙轻甲', quality: 'orange' },
  { id: 0x87, name: '25级橙重甲', quality: 'orange' },
  { id: 0x88, name: '25级橙板甲', quality: 'orange' },
  { id: 0x89, name: '35级橙布甲', quality: 'orange' },
  { id: 0x8a, name: '35级橙轻甲', quality: 'orange' },
  { id: 0x8b, name: '35级橙重甲', quality: 'orange' },
  { id: 0x8c, name: '35级橙板甲', quality: 'orange' },
  { id: 0x8d, name: '45级橙布甲', quality: 'orange' },
  { id: 0x8e, name: '45级橙轻甲', quality: 'orange' },
  { id: 0x8f, name: '45级橙重甲', quality: 'orange' },
  { id: 0x90, name: '45级橙板甲', quality: 'orange' },
  { id: 0x91, name: '55级橙布甲', quality: 'orange' },
  { id: 0x92, name: '55级橙轻甲', quality: 'orange' },
  { id: 0x93, name: '55级橙重甲', quality: 'orange' },
  { id: 0x94, name: '55级橙板甲', quality: 'orange' },
  { id: 0xba, name: '60级橙布甲', quality: 'orange' },
  { id: 0xbb, name: '60级橙轻甲', quality: 'orange' },
  { id: 0xbc, name: '60级橙重甲', quality: 'orange' },
  { id: 0xbd, name: '60级橙板甲', quality: 'orange' },
]

for (const cat of [
  { typeId: 0x04, name: '护肩' },
  { typeId: 0x05, name: '上衣' },
  { typeId: 0x06, name: '下衣' },
]) {
  for (const item of ARMOR_DEFS) {
    ITEM_DICTIONARY.push({
      typeId: cat.typeId,
      itemId: item.id,
      name: `${item.name} (${cat.name})`,
      categoryName: `防具-${cat.name}`,
      quality: item.quality,
      canRefine: true,
    })
  }
}

// 批量生成首饰类 (0x07 手腕, 0x08 戒指)
const WRIST_DEFS: { id: number; name: string; quality: 'pink' | 'orange' }[] = [
  { id: 0x29, name: '10粉手', quality: 'pink' },
  { id: 0x2a, name: '15粉手', quality: 'pink' },
  { id: 0x2b, name: '20粉手', quality: 'pink' },
  { id: 0x2c, name: '25粉手', quality: 'pink' },
  { id: 0x2d, name: '30粉手', quality: 'pink' },
  { id: 0x2e, name: '35粉手', quality: 'pink' },
  { id: 0x2f, name: '40粉手', quality: 'pink' },
  { id: 0x30, name: '45粉手', quality: 'pink' },
  { id: 0x31, name: '50粉手', quality: 'pink' },
  { id: 0x32, name: '55粉手', quality: 'pink' },
  { id: 0x33, name: '60粉手', quality: 'pink' },
  { id: 0x38, name: '30橙手', quality: 'orange' },
  { id: 0x39, name: '40橙手', quality: 'orange' },
  { id: 0x3a, name: '50橙手', quality: 'orange' },
  { id: 0x44, name: '60橙手A', quality: 'orange' },
  { id: 0x45, name: '60橙手B', quality: 'orange' },
  { id: 0x47, name: '60橙手C', quality: 'orange' },
  { id: 0x48, name: '60橙手D', quality: 'orange' },
  { id: 0x49, name: '60橙手E', quality: 'orange' },
  { id: 0x4a, name: '60橙手F', quality: 'orange' },
]

for (const item of WRIST_DEFS) {
  ITEM_DICTIONARY.push({
    typeId: 0x07,
    itemId: item.id,
    name: item.name,
    categoryName: '首饰-手腕',
    quality: item.quality,
    canRefine: true,
  })
}

const RING_DEFS: { id: number; name: string; quality: 'pink' | 'orange' }[] = [
  { id: 0x29, name: '10粉戒', quality: 'pink' },
  { id: 0x2a, name: '15粉戒', quality: 'pink' },
  { id: 0x2b, name: '20粉戒', quality: 'pink' },
  { id: 0x2c, name: '25粉戒', quality: 'pink' },
  { id: 0x2d, name: '30粉戒', quality: 'pink' },
  { id: 0x2e, name: '35粉戒', quality: 'pink' },
  { id: 0x2f, name: '40粉戒', quality: 'pink' },
  { id: 0x30, name: '45粉戒', quality: 'pink' },
  { id: 0x31, name: '50粉戒', quality: 'pink' },
  { id: 0x32, name: '55粉戒', quality: 'pink' },
  { id: 0x33, name: '60粉戒', quality: 'pink' },
  { id: 0x38, name: '30橙戒', quality: 'orange' },
  { id: 0x39, name: '40橙戒', quality: 'orange' },
  { id: 0x3a, name: '50橙戒', quality: 'orange' },
  { id: 0x47, name: '60橙戒A', quality: 'orange' },
  { id: 0x48, name: '60橙戒B', quality: 'orange' },
  { id: 0x4a, name: '60橙戒C', quality: 'orange' },
  { id: 0x4b, name: '60橙戒D', quality: 'orange' },
  { id: 0x4c, name: '60橙戒E', quality: 'orange' },
  { id: 0x4d, name: '60橙戒F', quality: 'orange' },
]

for (const item of RING_DEFS) {
  ITEM_DICTIONARY.push({
    typeId: 0x08,
    itemId: item.id,
    name: item.name,
    categoryName: '首饰-戒指',
    quality: item.quality,
    canRefine: true,
  })
}

// 快速查找函数
export function findItemInfo(typeId: number, itemId: number): { name: string; categoryName: string; quality?: string; canRefine: boolean } {
  const match = ITEM_DICTIONARY.find(i => i.typeId === typeId && i.itemId === itemId)
  if (match) {
    return {
      name: match.name,
      categoryName: match.categoryName,
      quality: match.quality,
      canRefine: !!match.canRefine || (typeId >= 0x00 && typeId <= 0x08),
    }
  }
  const cat = CATEGORIES.find(c => c.id === typeId)
  const catName = cat ? cat.name : `未知类别(0x${typeId.toString(16).padStart(2, '0')})`
  const isEquip = typeId >= 0x00 && typeId <= 0x08
  return {
    name: `${catName} [ID:0x${itemId.toString(16).padStart(2, '0')}]`,
    categoryName: catName,
    quality: 'white',
    canRefine: isEquip,
  }
}
