plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dnf.fix'
    compileSdk 34

    defaultConfig {
        applicationId "com.dnf.fix"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "dnf123456"
            keyAlias "dnffix"
            keyPassword "dnf123456"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // 纯轻量化零外部臃肿依赖
}
